update result check job
Signed-off-by: Yoichi Kawasaki <yokawasa@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,9 +15,11 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
         directories: |
           examples 
-    - name: Get output
-      run: echo "Issues found in previous step"
-      if: steps.sqlcheck.outputs.issue-found
+    - name: Check results
+      run: |
+        echo "Issues NOT found in previous step!"
+        exit 1
+      if: steps.sqlcheck.outputs.issue-found != "true"
 
   test2:
     runs-on: ubuntu-latest
@@ -37,7 +39,9 @@ jobs:
         directories: |
           examples 
           build/sql_dir
-          tests/sql_dir           
-    - name: Get output
-      run: echo "Issues found in previous step"
-      if: steps.sqlcheck.outputs.issue-found
+          tests/sql_dir
+    - name: Check results
+      run: |
+        echo "Issues NOT found in previous step!"
+        exit 1
+      if: steps.sqlcheck.outputs.issue-found != "true"
